### PR TITLE
added what can i do for fedora

### PR DESCRIPTION
**Pull request by vyaspranjal33**

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
This is great, thank you!! :tada:

**Comment by vyaspranjal33** [comment]
@nikhita  i think following lines should be added in description tab of repository
"This repository contains useful links to resources to help you get started with contributing to open sources concept by tapasweni pathak "

**Comment by nikhita** [comment]
I think the link is important as well. @tapawenipathak wdyt?

**Comment by vyaspranjal33** [comment]
i know i haven't removed or changed link/website i've just customized description tab :) @nikhita

**Pull request merged**
